version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: deployment/Dockerfile
    container_name: colossal_adventure
    volumes:
      - ../src:/app/src
      - postgres_data:/var/lib/postgresql/data
      - redis_data:/var/lib/redis
      - chromadb_data:/var/lib/chromadb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=colossal_adventure
      - REDIS_URL=redis://redis:6379
      - CHROMADB_PERSIST_DIR=/var/lib/chromadb
      - API_HOST=localhost
      - API_PORT=8000
      - TERM=xterm-256color
    tty: true
    stdin_open: true
    depends_on:
      - postgres
      - redis
      - chroma
    networks:
      - colossal_network

  postgres:
    image: postgres:15
    container_name: colossal_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=colossal_adventure
    networks:
      - colossal_network

  redis:
    image: redis:7
    container_name: colossal_redis
    volumes:
      - redis_data:/data
    networks:
      - colossal_network

  chroma:
    image: chromadb/chroma:latest
    container_name: colossal_chroma
    volumes:
      - chromadb_data:/chroma
    networks:
      - colossal_network

volumes:
  postgres_data:
  redis_data:
  chromadb_data:

networks:
  colossal_network:
    driver: bridge
